import type { ScriptId } from './scripts'

export interface Greeting {
  /** Stable anchor, React key, analytics key. Never key off array index. */
  id: string
  /** The artwork. Native script only, never mixed with transliteration. */
  word: string
  /** The small caption, and the source of the screen-reader label. */
  romanization: string
  /** Optional — not worth faking where the sources disagree. */
  ipa?: string
  /**
   * What the word literally says. This is the emotional payload of the whole
   * site: most greetings are not "hello", they are a small sentence about
   * peace, health, or being seen.
   */
  literal?: string
  language: { name: string; endonym: string; iso639: string }
  script: ScriptId
  /** Free text, deliberately. A language is not a country. */
  region: string
  /** 40-70 words on the custom. The reason the site exists. */
  note: string
  /** One sentence. Long etymology kills the pacing. */
  etymology: string
  /** Authorial multiplier applied on top of the measured fit-to-width. */
  typeScale: number
  /** em. Latin wants negative at display size; Arabic must stay at 0. */
  tracking?: number
}

export const GREETINGS: Greeting[] = [
  {
    id: 'en-hello',
    word: 'Hello',
    romanization: 'hello',
    ipa: '/həˈloʊ/',
    literal: 'hey there — stop',
    language: { name: 'English', endonym: 'English', iso639: 'en' },
    script: 'latn',
    region: 'Much of the world, by accident of empire',
    note: 'The youngest word on this list by a wide margin. Before the 1800s it was not a greeting at all — it was a shout, used to hail a ferryman across water or to urge on hounds. Thomas Edison proposed it as the right thing to say into a telephone, against Alexander Graham Bell, who wanted "ahoy"; the exchange operators are what made it stick. A machine taught us this one.',
    etymology: 'From the hunting and hailing cry holla, standardised by the telephone exchange in the 1880s.',
    typeScale: 1.1,
    tracking: -0.025,
  },
  {
    id: 'yo-bawo',
    word: 'Báwo ni',
    romanization: 'báwo ni',
    ipa: '/bá.wo ni/',
    literal: 'how is it?',
    language: { name: 'Yoruba', endonym: 'Èdè Yorùbá', iso639: 'yo' },
    script: 'latn',
    region: 'Southwestern Nigeria, Benin, and Togo',
    note: 'Yoruba greeting is a body before it is a sentence. Traditionally a young man prostrates full length — dòbálẹ̀ — and a young woman kneels, kúnlẹ̀, when greeting an elder. There are separate greetings for morning, for finding someone at work, for finding them resting, and for having not seen them in a while. To greet badly is a visible failure of upbringing.',
    etymology: 'báwo, "how", with ni, "is it" — a question that never expects a real answer.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'ja-konnichiwa',
    word: 'こんにちは',
    romanization: 'konnichiwa',
    ipa: '/kon.ni.tɕi.wa/',
    literal: 'as for this day…',
    language: { name: 'Japanese', endonym: '日本語', iso639: 'ja' },
    script: 'jpan',
    region: 'Japan',
    note: 'An unfinished sentence. The full phrase asked after how your day was going, and over centuries the question wore away until only its opening survived. Japanese greeting is layered on top of it: the bow carries the meaning the words dropped, its depth scaled to respect, and a deep bow with no words at all is a complete greeting.',
    etymology: 'A clipping of 今日は — "as for today" — with the question that followed it worn away entirely.',
    typeScale: 1,
  },
  {
    id: 'hi-namaste',
    word: 'नमस्ते',
    romanization: 'namaste',
    ipa: '/nə.məs.teː/',
    literal: 'I bow to you',
    language: { name: 'Hindi', endonym: 'हिन्दी', iso639: 'hi' },
    script: 'deva',
    region: 'North India and Nepal',
    note: 'Said with the palms pressed together at the chest, fingers upward, head inclined. The gesture is the greeting; the word only narrates it. Because it requires no contact, it travels well — it has been borrowed across the world by people who never learned that they are saying, quite literally, that they are bowing.',
    etymology: 'Sanskrit namas, "bow", fused with te, "to you".',
    typeScale: 0.96,
  },
  {
    id: 'ar-salam',
    word: 'السلام عليكم',
    romanization: 'as-salāmu ʿalaykum',
    ipa: '/as.sa.laː.mu ʕa.laj.kum/',
    literal: 'peace be upon you',
    language: { name: 'Arabic', endonym: 'العربية', iso639: 'ar' },
    script: 'arab',
    region: 'North Africa, the Levant, and the Gulf',
    note: 'Not a word but a wish, and one that obliges a reply: wa ʿalaykumu s-salām, and upon you, peace. The grammar is plural even when you greet one person, which folds in everyone standing with them. It is spoken daily across some two dozen countries, by around half a billion people — which is exactly why no single flag belongs beside it.',
    etymology: 'From the root s-l-m, which also gives salām, islām, and muslim — a root meaning wholeness and safety.',
    typeScale: 0.82,
    tracking: 0,
  },
  {
    id: 'zu-sawubona',
    word: 'Sawubona',
    romanization: 'sawubona',
    ipa: '/sawuˈɓɔna/',
    literal: 'we see you',
    language: { name: 'Zulu', endonym: 'isiZulu', iso639: 'zu' },
    script: 'latn',
    region: 'South Africa',
    note: 'The answer is yebo, sawubona — yes, we see you too. The "we" is not politeness: the speaker greets on behalf of a family and the ancestors behind them, so you are seen by more than the person in front of you. The plural form, sanibonani, addresses a group. Few greetings state their own function so plainly.',
    etymology: 'A contraction of siyakubona — si-, "we", plus -bona, "to see": the seeing is done by a community.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'ko-annyeong',
    word: '안녕하세요',
    romanization: 'annyeonghaseyo',
    ipa: '/an.njʌŋ.ha.se.jo/',
    literal: 'are you at peace?',
    language: { name: 'Korean', endonym: '한국어', iso639: 'ko' },
    script: 'hang',
    region: 'The Korean peninsula',
    note: 'Korean does not have one hello; it has a register for every relationship. Annyeonghaseyo is the polite middle. Drop to annyeong with a close friend, climb to annyeonghasimnikka in a formal address. Choosing wrongly is not a grammatical error so much as a social one — the word you pick declares what you think the two of you are to each other.',
    etymology: 'From Sino-Korean 安寧 — peace, tranquillity — turned into a question.',
    typeScale: 0.92,
  },
  {
    id: 'he-shalom',
    word: 'שָׁלוֹם',
    romanization: 'shalom',
    ipa: '/ʃaˈlom/',
    literal: 'wholeness',
    language: { name: 'Hebrew', endonym: 'עברית', iso639: 'he' },
    script: 'hebr',
    region: 'Israel and the Jewish diaspora',
    note: 'One word for hello, for goodbye, and for peace — and the peace it names is not merely the absence of war but a state of being complete, unbroken, with nothing missing. To greet someone with it is to wish them intactness. It shares a root with Arabic salām; the two languages say nearly the same thing to each other.',
    etymology: 'From the root sh-l-m, "to be whole, to be complete".',
    typeScale: 0.9,
    tracking: 0,
  },
  {
    id: 'zh-nihao',
    word: '你好',
    romanization: 'nǐ hǎo',
    ipa: '/ni˧˥ xɑʊ̯˨˩˦/',
    literal: 'you — good',
    language: { name: 'Mandarin Chinese', endonym: '中文', iso639: 'zh' },
    script: 'hans',
    region: 'China, Taiwan, and Singapore',
    note: 'Two characters, no verb: you, good. It is a statement rather than a question, and it is also surprisingly modern — for most of Chinese history people greeted each other by asking whether you had eaten yet, 你吃了吗, which in many places they still do. A greeting that asks after your hunger tells you what the century was like.',
    etymology: '你 (you) plus 好 (good) — among the first phrases taught to every learner of the language.',
    typeScale: 1.08,
  },
  {
    id: 'ru-zdravstvuyte',
    word: 'Здравствуйте',
    romanization: 'zdravstvuyte',
    ipa: '/ˈzdrastvʊjtʲe/',
    literal: 'be healthy',
    language: { name: 'Russian', endonym: 'русский', iso639: 'ru' },
    script: 'cyrl',
    region: 'Russia and much of Central Asia',
    note: 'Twelve letters, and native speakers compress them into something closer to "zdrastvuyte" — the middle collapses under its own weight. It is an imperative: be healthy, stay well. The informal zdravstvuy and the casual privet exist, but the long form is the one you owe a stranger, and its sheer length is part of the courtesy.',
    etymology: 'From zdravie, "health" — an old imperative to be in good health.',
    typeScale: 0.76,
    tracking: -0.025,
  },
  {
    id: 'th-sawatdee',
    word: 'สวัสดี',
    romanization: 'sawatdee',
    ipa: '/sà.wàt.diː/',
    literal: 'well-being, blessing',
    language: { name: 'Thai', endonym: 'ภาษาไทย', iso639: 'th' },
    script: 'thai',
    region: 'Thailand',
    note: 'Accompanied by the wai: palms together, fingertips rising toward the face, head bowing to meet them. The higher the hands, the greater the deference. What is striking is the age of the word — it is not ancient at all. It was coined in the 1930s by a professor at Chulalongkorn University and promoted by the state. A nation decided how it would say hello, and then it did.',
    etymology: 'From Sanskrit svasti, "well-being" — the same root as the much older svastika symbol.',
    typeScale: 0.9,
  },
  {
    id: 'sw-habari',
    word: 'Habari',
    romanization: 'habari',
    ipa: '/haˈbari/',
    literal: 'news?',
    language: { name: 'Swahili', endonym: 'Kiswahili', iso639: 'sw' },
    script: 'latn',
    region: 'The East African coast',
    note: 'You do not ask how someone is; you ask what the news is. The expected answer is nzuri — good — regardless of whether it is, because the exchange is a courtesy rather than an interview. Swahili is a trade language, grown along a coast where Bantu speakers met Arab merchants, and habari itself is a loan word from that meeting.',
    etymology: 'Borrowed from Arabic khabar, "news" — a word that sailed down the coast with the monsoon trade.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'el-yiasou',
    word: 'Γεια σου',
    romanization: 'yia sou',
    ipa: '/ʝa su/',
    literal: 'health to you',
    language: { name: 'Greek', endonym: 'Ελληνικά', iso639: 'el' },
    script: 'grek',
    region: 'Greece and Cyprus',
    note: 'The same wish as the Russian one, arrived at independently: your health. Use sou for one person you know, sas for a stranger or for several. Greeks also kept khaire from the ancient world — "rejoice" — and its plural, chairete, is what a runner is said to have gasped in Athens, having run from Marathon, before dying. Health for the living, joy for the victorious.',
    etymology: 'From υγεία, "health", worn down in everyday speech to γειά.',
    typeScale: 0.9,
    tracking: -0.02,
  },
  {
    id: 'mi-kiaora',
    word: 'Kia ora',
    romanization: 'kia ora',
    ipa: '/ki.a ˈɔ.ɾa/',
    literal: 'be well, have life',
    language: { name: 'Māori', endonym: 'te reo Māori', iso639: 'mi' },
    script: 'latn',
    region: 'Aotearoa New Zealand',
    note: 'A wish for life itself. It also works as thanks, as agreement, and as encouragement — a single phrase doing the work of several. Alongside it is the hongi: two people press noses and foreheads together and share one breath. The visitor stops being a visitor at that moment. Few greetings are so explicit that something has changed.',
    etymology: 'kia, a particle of wishing, plus ora — life, health, being well.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'am-selam',
    word: 'ሰላም',
    romanization: 'selam',
    ipa: '/sɛˈlam/',
    literal: 'peace',
    language: { name: 'Amharic', endonym: 'አማርኛ', iso639: 'am' },
    script: 'ethi',
    region: 'Ethiopia',
    note: 'Written in Geʽez script, which came from South Arabia and was remade in the Horn of Africa into an abugida — each character a syllable rather than a letter — and has been in daily use ever since. The greeting itself belongs to the same Semitic family as shalom and salām — three peoples, three scripts, one word for peace, separated by a few thousand years of drift.',
    etymology: 'Semitic s-l-m, the shared root behind shalom and salām.',
    typeScale: 0.95,
  },
  {
    id: 'ta-vanakkam',
    word: 'வணக்கம்',
    romanization: 'vaṇakkam',
    ipa: '/ʋaɳakkam/',
    literal: 'I offer you reverence',
    language: { name: 'Tamil', endonym: 'தமிழ்', iso639: 'ta' },
    script: 'taml',
    region: 'Tamil Nadu, Sri Lanka, and Singapore',
    note: 'Spoken by people whose language has been written continuously for more than two thousand years — Tamil is among the oldest living literary languages on earth. The greeting is offered with joined palms, like namaste, but the word comes from a different root entirely: vanangu, to bend, to salute, to pay homage. You are not describing a bow. You are performing one.',
    etymology: 'From vaṇaṅku, "to bow or pay homage", with a suffix that turns the act into a noun.',
    typeScale: 0.82,
  },
  {
    id: 'bn-nomoshkar',
    word: 'নমস্কার',
    romanization: 'nomoshkar',
    ipa: '/nɔmoʃkar/',
    literal: 'I make my bow',
    language: { name: 'Bengali', endonym: 'বাংলা', iso639: 'bn' },
    script: 'beng',
    region: 'Bangladesh and West Bengal',
    note: 'Cousin to namaste, from the same Sanskrit root, but with its own script and its own weight. Bengali carries a second greeting alongside it — the Muslim as-salāmu ʿalaykum — and which one you use tends to follow community rather than country. The border drawn through Bengal in 1947 did not divide the language; it only divided the hello.',
    etymology: 'Sanskrit namas, "bow", plus kāra, "the making of" — the act of bowing.',
    typeScale: 0.86,
  },
  {
    id: 'tr-merhaba',
    word: 'Merhaba',
    romanization: 'merhaba',
    ipa: '/ˈmæɾ.ha.ba/',
    literal: 'a wide, open space',
    language: { name: 'Turkish', endonym: 'Türkçe', iso639: 'tr' },
    script: 'latn',
    region: 'Türkiye',
    note: 'The loveliest etymology on this list. The Arabic it comes from evokes a broad open place — the sense being that there is room for you here, that you have arrived somewhere spacious rather than crowded. Turkish wrote it in Arabic script until 1928, when the alphabet changed by decree in a matter of months. The word stayed; its clothes changed.',
    etymology: 'From Arabic marḥaban, related to raḥb, "wide, roomy" — "you have come to a spacious place".',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'fa-salam',
    word: 'سلام',
    romanization: 'salâm',
    ipa: '/sæˈlɒːm/',
    literal: 'peace',
    language: { name: 'Persian', endonym: 'فارسی', iso639: 'fa' },
    script: 'arab',
    region: 'Iran, Afghanistan, and Tajikistan',
    note: 'Persian borrowed the Arabic word and kept it short. What surrounds it is the elaborate courtesy called taarof — a ritual of offering, refusing, and offering again, in which a shopkeeper may insist the goods are worthless and you must insist on paying. The greeting is one word. The etiquette that follows can take several minutes.',
    etymology: 'The Arabic salām, adopted whole into Persian and kept in its shortest form.',
    typeScale: 0.85,
    tracking: 0,
  },
  {
    id: 'ka-gamarjoba',
    word: 'გამარჯობა',
    romanization: 'gamarjoba',
    ipa: '/ɡɑmɑrdʒobɑ/',
    literal: 'victory to you',
    language: { name: 'Georgian', endonym: 'ქართული', iso639: 'ka' },
    script: 'geor',
    region: 'Georgia, in the Caucasus',
    note: 'You wish a stranger victory, and they answer gagimarjos — victory to you too. The story attached to it is that soldiers returning from war announced the outcome before anything else, and the announcement became the greeting. Georgian is written in Mkhedruli, which it shares with its Kartvelian relatives — Mingrelian, Svan and Laz — and with nothing outside that family.',
    etymology: 'From gamarjveba, "victory" — a battlefield report that hardened into a hello.',
    typeScale: 0.8,
  },
  {
    id: 'haw-aloha',
    word: 'Aloha',
    romanization: 'aloha',
    ipa: '/əˈloʊhɑ/',
    literal: 'love, compassion',
    language: { name: 'Hawaiian', endonym: 'ʻŌlelo Hawaiʻi', iso639: 'haw' },
    script: 'latn',
    region: 'Hawaiʻi',
    note: 'Commonly read as alo, presence or face, with hā, breath — the sharing of breath, which is what happens in the honi, where foreheads and noses touch. That parse is folk etymology; the word is old Polynesian for love, and is cognate with Māori aroha. It means hello, goodbye and love, and it survived a period when the language itself was banned in schools.',
    etymology: 'From Proto-Polynesian qarofa, "love, compassion" — cognate with Māori aroha and Samoan alofa.',
    typeScale: 1.05,
    tracking: -0.02,
  },
  {
    id: 'mn-sainbainauu',
    word: 'Сайн байна уу',
    romanization: 'sain baina uu',
    ipa: '/sæːm bæːn ʊː/',
    literal: 'are you well?',
    language: { name: 'Mongolian', endonym: 'Монгол хэл', iso639: 'mn' },
    script: 'cyrl',
    region: 'Mongolia',
    note: 'Written here in Cyrillic, adopted in the 1940s, though the older vertical Mongol script — written top to bottom, columns running left to right — is being taught again. On the steppe the greeting that mattered was different: people asked after your animals. Whether your livestock had wintered well was the same question as whether you had.',
    etymology: 'sain, "good or well", with the question particle uu.',
    typeScale: 0.72,
    tracking: -0.02,
  },
  {
    id: 'vi-xinchao',
    word: 'Xin chào',
    romanization: 'xin chào',
    ipa: '/sin t͡ɕaːw/',
    literal: 'I beg to greet',
    language: { name: 'Vietnamese', endonym: 'Tiếng Việt', iso639: 'vi' },
    script: 'latn',
    region: 'Vietnam',
    note: 'Textbook Vietnamese, and slightly too formal for daily use — in practice you greet someone with the pronoun that states your relative age and standing, chào anh, chào chị, chào em. You cannot say hello without first deciding who is older. The language is written in Latin letters because Portuguese and French missionaries devised the system; it replaced Chinese characters entirely.',
    etymology: 'xin, "to ask or beg", with chào, "to greet".',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'km-suostei',
    word: 'សួស្តី',
    romanization: 'suostei',
    ipa: '/suə.sdəj/',
    literal: 'good fortune',
    language: { name: 'Khmer', endonym: 'ភាសាខ្មែរ', iso639: 'km' },
    script: 'khmr',
    region: 'Cambodia',
    note: 'Offered with the sampeah, palms together, the height of the hands rising with the status of the person before you — chest for a peer, brow for a monk. Khmer has no spaces between words and the largest alphabet in the world, seventy-four letters. Like Thai sawatdee, the greeting descends from the Sanskrit svasti, carried east by Indian traders and never sent back.',
    etymology: 'From Sanskrit svasti, "well-being, good fortune".',
    typeScale: 0.88,
  },
  {
    id: 'hy-barev',
    word: 'Բարև',
    romanization: 'barev',
    ipa: '/bɑˈɾɛv/',
    literal: 'with good',
    language: { name: 'Armenian', endonym: 'Հայերեն', iso639: 'hy' },
    script: 'armn',
    region: 'Armenia and its diaspora',
    note: 'Often explained as "good sun", which is folk etymology — it is the old instrumental of bari, "good", so you hand someone the word itself. The fuller barev dzez is what you give a stranger. The alphabet it is written in was made by one man, Mesrop Mashtots, around 405 AD, specifically so that Armenians could read scripture in their own tongue — and it is still in use, largely unchanged, sixteen centuries later. Few designs last that well.',
    etymology: 'From Old Armenian bareaw, the instrumental of bari, "good" — "with good".',
    typeScale: 0.94,
  },
  {
    id: 'fi-terve',
    word: 'Terve',
    romanization: 'terve',
    ipa: '/ˈterʋe/',
    literal: 'healthy',
    language: { name: 'Finnish', endonym: 'suomi', iso639: 'fi' },
    script: 'latn',
    region: 'Finland',
    note: 'Health again — the third time on this list, from a language related to none of the others. Terve is the casual, faintly old-fashioned one; hei and moi do the everyday work. Finnish greeting culture is economical: the word, a nod, and no obligation to fill the silence that follows. Silence between two Finns is not an awkwardness to be repaired. It is a normal condition of being in a room together.',
    etymology: 'From terve, "healthy, sound" — the adjective used bare, as a wish.',
    typeScale: 1.05,
    tracking: -0.02,
  },
  {
    id: 'ga-diaduit',
    word: 'Dia duit',
    romanization: 'dia duit',
    ipa: '/dʲiə ˈdˠɪtʲ/',
    literal: 'God to you',
    language: { name: 'Irish', endonym: 'Gaeilge', iso639: 'ga' },
    script: 'latn',
    region: 'Ireland',
    note: 'The reply raises the stakes: Dia is Muire duit — God and Mary be with you. A third person may answer with God, Mary and Patrick. It is a greeting that escalates, each speaker adding a saint. Irish is the first official language of the state and the daily language of a small minority, which makes every hello in it a small act of maintenance.',
    etymology: 'Dia, "God", with duit, "to you" — a blessing shortened into a greeting.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'bo-tashidelek',
    word: 'བཀྲ་ཤིས་བདེ་ལེགས།',
    romanization: 'tashi delek',
    ipa: '/tʰa.ɕi de.leʔ/',
    literal: 'may auspiciousness and goodness come',
    language: { name: 'Tibetan', endonym: 'བོད་སྐད་', iso639: 'bo' },
    script: 'tibt',
    region: 'The Tibetan plateau and the Himalaya',
    note: 'Not a hello so much as a blessing you hand over. Traditionally it arrives with a khata, a white silk scarf, draped over the receiver’s hands or shoulders. The dots between the syllables are tsheg, separating syllables rather than words, and the small vertical stroke at the end closes the sentence. The script reads left to right and stacks vertically at once.',
    etymology: 'bkra shis, "auspicious", with bde legs, "well and good".',
    typeScale: 0.66,
  },
  {
    id: 'wo-nangadef',
    word: 'Nanga def',
    romanization: 'nanga def',
    ipa: '/naŋɡa dɛf/',
    literal: 'how do you do?',
    language: { name: 'Wolof', endonym: 'Wolof', iso639: 'wo' },
    script: 'latn',
    region: 'Senegal, the Gambia, and Mauritania',
    note: 'The answer is maangi fi rekk — I am here, only. Not well, not badly: present. What follows is a long chain of enquiries after your family, your household, your peace, each with its own fixed reply, and cutting it short is the rude part. Greeting in Wolof is not the doorway to a conversation. It is a conversation.',
    etymology: 'From def, "to do" — literally asking what you are doing, or how you are faring.',
    typeScale: 1,
    tracking: -0.02,
  },
  {
    id: 'iu-ai',
    word: 'ᐊᐃᓐᖓᐃ',
    romanization: 'ainngai',
    ipa: '/aiŋŋai/',
    literal: 'hello',
    language: { name: 'Inuktitut', endonym: 'ᐃᓄᒃᑎᑐᑦ', iso639: 'iu' },
    script: 'cans',
    region: 'Arctic Canada',
    note: 'Written in syllabics, where the direction a character points tells you its vowel — the same shape rotated four ways. The system was adapted for Inuktitut from one devised for Cree, and it is now on road signs and government documents across Nunavut, where Inuktitut is official alongside English and French. Around forty thousand people speak it, and the script does much of the work of keeping them.',
    etymology: 'A greeting particle; the alternate ᐊᐃ (ai) is the shorter everyday form.',
    typeScale: 0.92,
  },
  {
    id: 'ha-sannu',
    word: 'Sannu',
    romanization: 'sannu',
    ipa: '/\u02c8sannu/',
    literal: 'gently',
    language: { name: 'Hausa', endonym: 'Harshen Hausa', iso639: 'ha' },
    script: 'latn',
    region: 'Northern Nigeria, Niger, and across the Sahel',
    note: 'The same word carries sympathy. Say it to someone hauling a load and it means roughly "easy now, I see what that costs you" \u2014 a greeting that acknowledges effort rather than ignoring it. Hausa is the trade language of the Sahel, and for centuries it was written in Ajami, an Arabic script adapted for it, long before the Latin Boko alphabet arrived.',
    etymology: 'From sannu, "slowly, gently" \u2014 the same word used to console and to commend.',
    typeScale: 1.08,
    tracking: -0.02,
  },
  {
    id: 'ig-kedu',
    word: 'Kèdụ',
    romanization: 'kèdụ',
    ipa: '/kè.dʊ́/',
    literal: 'how?',
    language: { name: 'Igbo', endonym: 'As\u1ee5s\u1ee5 Igbo', iso639: 'ig' },
    script: 'latn',
    region: 'Southeastern Nigeria',
    note: 'A question so short it barely is one. Alongside it sits Ndeewo, the respectful form you owe an elder. Igbo has dozens of dialects and Standard Igbo is a twentieth-century construction assembled from several of them \u2014 so which greeting you reach for, and how you tone it, quietly says where you are from.',
    etymology: 'From kedu, "how" \u2014 the opening of a longer question that stopped needing the rest.',
    typeScale: 1.1,
    tracking: -0.02,
  },
  {
    id: 'pcm-howfar',
    word: 'How far?',
    romanization: 'how far',
    ipa: '/ha\u028a fa/',
    literal: 'how far?',
    language: { name: 'Nigerian Pidgin', endonym: 'Naij\u00e1', iso639: 'pcm' },
    script: 'latn',
    region: 'Nigeria and much of West Africa',
    note: 'English words running on West African grammar, spoken by something like a hundred million people, though only a few million of them as a first language. The answer is "I dey": I am here. For decades it was dismissed as broken English by people who spoke it fluently at home. It now has its own BBC news service.',
    etymology: 'English "how far", reshaped into a complete greeting by a language that keeps only what it needs.',
    typeScale: 1.0,
    tracking: -0.025,
  },
  {
    id: 'ff-jamna',
    word: 'Jam na?',
    romanization: 'jam na',
    ipa: '/d\u0292am na/',
    literal: 'peace?',
    language: { name: 'Fulfulde', endonym: 'Fulfulde', iso639: 'ff' },
    script: 'latn',
    region: 'From Senegal to Sudan, across the Sahel',
    note: 'The reply is jam tan \u2014 peace only. The question changes with the hour: jam waali, did you pass the night in peace; jam nyalli, the afternoon; jam hiiri, the evening. The Fulani are among the largest pastoral peoples on earth, and this is the third unrelated language family on this list to settle on peace as its hello.',
    etymology: 'From jam, "peace" \u2014 a cousin in meaning, not in root, to shalom and sal\u0101m.',
    typeScale: 1.05,
    tracking: -0.02,
  },
  {
    id: 'efi-mesiere',
    word: 'Emesiere',
    romanization: 'emesiere',
    language: { name: 'Efik', endonym: 'Usem Efik', iso639: 'efi' },
    script: 'latn',
    region: 'Cross River, southeastern Nigeria',
    literal: 'you have woken',
    note: 'A morning greeting; the reply is Emesiere nde. Efik marks who it is aimed at \u2014 amesiere to one person, emesiere to several or to an elder \u2014 and Esiere closes the day the same way. The language was among the first in Nigeria to be written down and printed, by Presbyterian missionaries in Calabar from the 1840s, which is why an Efik dictionary is older than most European colonial borders in Africa.',
    etymology: 'The perfective me- on siere, "to wake, to dawn", behind a prefix naming who is addressed.',
    typeScale: 1.0,
    tracking: -0.02,
  },
  {
    id: 'kr-ushe',
    word: 'Wushe wushe',
    romanization: 'wushe wushe',
    ipa: '/wu\u0283e wu\u0283e/',
    language: { name: 'Kanuri', endonym: 'Kanuri', iso639: 'kr' },
    script: 'latn',
    region: 'Borno and the Lake Chad basin',
    note: 'Wushe alone is thanks, or well done, and it takes its meaning from what follows \u2014 wushe cidaro to someone working, wushe baba to an elder. Doubled it becomes a greeting, and also the name of the welcome held the night before a wedding. Kanuri is the language of the thousand-year Kanem\u2013Bornu Empire, and the only Nilo-Saharan entry here.',
    etymology: 'From wushe, "well done, thanks" \u2014 a formula that takes its sense from whatever follows it.',
    typeScale: 0.9,
    tracking: -0.02,
  },
]
