// GENERATED by scripts/generate-crowd.mjs — do not edit by hand.
// Regenerate with `pnpm run crowd`. Seeded, so output is byte-stable.
//
// The artwork itself lives in public/crowd-light.svg and public/crowd-dark.svg.
// Inlining it put the drawing in the document twice — streamed HTML plus the
// RSC payload — so it is served as a cached file instead and this module holds
// only what the page needs to describe it.
//
// Artwork: Notionists by Zoish, from DiceBear's CC0 collection. Public domain,
// free commercially, no attribution required.

export const CROWD_WIDTH = 1400
export const CROWD_HEIGHT = 430
export const CROWD_COUNT = 45
