import { Geist, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'
import type { ScriptId } from '@/content/scripts'

/**
 * Latin body copy and chrome. `swap` plus metric matching is right here — a
 * brief fallback render of Latin text is harmless, and matching the metrics
 * keeps CLS at zero across the swap.
 */
export const geist = Geist({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-geist',
  display: 'swap',
  fallback: ['system-ui', 'sans-serif'],
  adjustFontFallback: true,
})

export const geistMono = Geist_Mono({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-geist-mono',
  display: 'swap',
  fallback: ['ui-monospace', 'monospace'],
  adjustFontFallback: true,
})

/**
 * The script faces.
 *
 * Each is a build-time subset containing only the glyphs that greeting
 * actually renders — 1 to 14 KB apiece, against tens of megabytes for the full
 * Noto families.
 *
 * `display: 'block'` rather than `swap` or `optional`, deliberately: the
 * fallback render for a Japanese word on a machine with no CJK font is five
 * tofu boxes, and swapping *from* tofu is far worse than a brief blank. These
 * are tiny, same-origin and preloaded, so the 3s block period is never reached.
 *
 * `adjustFontFallback: false` because metric-matching a Khmer face against
 * Arial is meaningless.
 *
 * next/font requires each loader call to sit at module scope with literal
 * arguments, so these cannot be generated by a helper.
 */
const notoLatn = localFont({
  src: '../assets/fonts/latn-subset.woff2',
  variable: '--font-noto-latn',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoJpan = localFont({
  src: '../assets/fonts/jpan-subset.woff2',
  variable: '--font-noto-jpan',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoHans = localFont({
  src: '../assets/fonts/hans-subset.woff2',
  variable: '--font-noto-hans',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoHang = localFont({
  src: '../assets/fonts/hang-subset.woff2',
  variable: '--font-noto-hang',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoArab = localFont({
  src: '../assets/fonts/arab-subset.woff2',
  variable: '--font-noto-arab',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoHebr = localFont({
  src: '../assets/fonts/hebr-subset.woff2',
  variable: '--font-noto-hebr',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoDeva = localFont({
  src: '../assets/fonts/deva-subset.woff2',
  variable: '--font-noto-deva',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoBeng = localFont({
  src: '../assets/fonts/beng-subset.woff2',
  variable: '--font-noto-beng',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoTaml = localFont({
  src: '../assets/fonts/taml-subset.woff2',
  variable: '--font-noto-taml',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoThai = localFont({
  src: '../assets/fonts/thai-subset.woff2',
  variable: '--font-noto-thai',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoKhmr = localFont({
  src: '../assets/fonts/khmr-subset.woff2',
  variable: '--font-noto-khmr',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoCyrl = localFont({
  src: '../assets/fonts/cyrl-subset.woff2',
  variable: '--font-noto-cyrl',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoGrek = localFont({
  src: '../assets/fonts/grek-subset.woff2',
  variable: '--font-noto-grek',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoGeor = localFont({
  src: '../assets/fonts/geor-subset.woff2',
  variable: '--font-noto-geor',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoArmn = localFont({
  src: '../assets/fonts/armn-subset.woff2',
  variable: '--font-noto-armn',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoEthi = localFont({
  src: '../assets/fonts/ethi-subset.woff2',
  variable: '--font-noto-ethi',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoTibt = localFont({
  src: '../assets/fonts/tibt-subset.woff2',
  variable: '--font-noto-tibt',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const notoCans = localFont({
  src: '../assets/fonts/cans-subset.woff2',
  variable: '--font-noto-cans',
  display: 'block',
  preload: true,
  adjustFontFallback: false,
  weight: '500',
  style: 'normal',
})

const ALL = [geist, geistMono, notoLatn, notoJpan, notoHans, notoHang, notoArab, notoHebr, notoDeva, notoBeng, notoTaml, notoThai, notoKhmr, notoCyrl, notoGrek, notoGeor, notoArmn, notoEthi, notoTibt, notoCans]

/** Every font variable, for the <html> className. */
export const fontVariables = ALL.map((f) => f.variable).join(' ')

/**
 * The font stack for a hero word, by script.
 *
 * Latin words lead with Geist and fall through to the Noto subset for the
 * glyphs Geist lacks — Vietnamese tone stacks, Yoruba sub-dots.
 */
export const SCRIPT_FONT_STACK: Record<ScriptId, string> = {
  latn: 'var(--font-geist), var(--font-noto-latn), sans-serif',
  jpan: 'var(--font-noto-jpan), sans-serif',
  hans: 'var(--font-noto-hans), sans-serif',
  hang: 'var(--font-noto-hang), sans-serif',
  arab: 'var(--font-noto-arab), serif',
  hebr: 'var(--font-noto-hebr), sans-serif',
  deva: 'var(--font-noto-deva), sans-serif',
  beng: 'var(--font-noto-beng), sans-serif',
  taml: 'var(--font-noto-taml), sans-serif',
  thai: 'var(--font-noto-thai), sans-serif',
  khmr: 'var(--font-noto-khmr), sans-serif',
  cyrl: 'var(--font-noto-cyrl), sans-serif',
  grek: 'var(--font-noto-grek), sans-serif',
  geor: 'var(--font-noto-geor), sans-serif',
  armn: 'var(--font-noto-armn), sans-serif',
  ethi: 'var(--font-noto-ethi), sans-serif',
  tibt: 'var(--font-noto-tibt), serif',
  cans: 'var(--font-noto-cans), sans-serif',
}
